### ISSUE TITLE
安卓版本4.4.4，运行报错

### ISSUE THREAD

**Issue by WaterEye0o** [liuchungui/react-native-umeng-push#12]
官方说U-PushSDK支持安卓的最低版本是3.0.0，在别的安卓版本中是正常可以用的，但是到了安卓版本4.4.4运行就报这个错误
FATAL EXCEPTION: main
Process: com.handson, PID: 2594
java.lang.NoClassDefFoundError: com.umeng.message.tag.TagManager
at com.umeng.message.PushAgent.<init>(PushAgent.java:68)
at com.umeng.message.PushAgent.getInstance(PushAgent.java:89)
at com.liuchungui.react_native_umeng_push.UmengPushApplication.enablePush(UmengPushApplication.java:46)
at com.liuchungui.react_native_umeng_push.UmengPushApplication.onCreate(UmengPushApplication.java:31)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
at android.app.ActivityThread.access$1500(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

**Comment by liuchungui** [comment]
@WaterEye0o 就只是在4.4.4上面有问题？
嗯，我这几天到时看看

**Comment by WaterEye0o** [comment]
@liuchungui 我就测试了4.4.4的机型，5.0以上的没有问题

**Comment by dongchuanlei** [comment]
这个应该是和分包有关系, 可以看看这个:
http://www.jianshu.com/p/5dd2a7a4e6aa
