### ISSUE TITLE
android crash:java.lang.NoClassDefFoundError: com.umeng.message.protobuffer.PushRequest$entityEncodingFormat

### ISSUE THREAD

**Issue by imyyg2008** [liuchungui/react-native-umeng-push#24]
crash log
java.lang.NoClassDefFoundError: com.umeng.message.protobuffer.PushRequest$entityEncodingFormat
	at com.umeng.message.proguard.I.a(NetworkHelper.java:266)
	at com.umeng.message.UTrack.addExclusiveAlias(UTrack.java:823)
	at com.umeng.message.UTrack$2.run(UTrack.java:624)
	at java.lang.Thread.run(Thread.java:833)

**Comment by imyyg2008** [comment]
友盟的论坛上说可能与支付宝的sdk有关，但是没有解决方法

**Comment by liuchungui** [comment]
@imyyg2008 是否更新umeng的版本就能搞定？
